### ISSUE TITLE
Hydration error

### ISSUE THREAD

**Issue by teleskop150750** [ubugeeei/reading-vuejs-core-vapor#70]
https://github.com/user-attachments/assets/89afe357-e836-45ee-a946-50eae42b9d73

**Comment by ubugeeei** [comment]
@teleskop150750 

Thank you for the submission!
It seems to be a VitePress issue, so I’ve created an issue there.

https://github.com/vuejs/vitepress/issues/4231

**Comment by brc-dd** [comment]
adjust https://github.com/ubugeeei/reading-vuejs-core-vapor/blob/main/.vitepress/plugins/markdown-it/github/index.ts to this:

```ts
export const previewGitHubSource: PluginSimple = (md) => {
  md.block.ruler.before('paragraph', 'github_link_block', (state, startLine) => {
    const line = state.getLines(startLine, startLine + 1, state.blkIndent, false).trim()

    if (!isGithubUrl(line)) {
      return false
    }

    const token = state.push('github_link', '', 0)
    token.content = line
    token.map = [startLine, startLine + 1]

    state.line = startLine + 1

    return true
  })

  md.renderer.rules.github_link = (tokens, idx) => {
    const c = tokens[idx].content
    const rawHtml = fetchHtmlSync(c)
    const parsed = parse(rawHtml, c)
    const res = renderToHtml(parsed)
    return res
  }
}
```

**Comment by ubugeeei** [comment]
Wow... how kind you are...
Even though I was just writing the plugin incorrectly, you went as far as proposing code to the repository. 
It’s completely fixed! Thank you so much...! 💚
